- type: application/vnd.org.wtwta.project
  main: x-cweb
  id: x-cweb

  env: . ./profile.sh

  scripts:
    init:
      - ./install-dependencies.sh
    deinit:
      - git clean -df
    build:
      - make -k build
    doc:
      - make -k doc
    test:
      - make test
